apiVersion: apps/v1
kind: Deployment
metadata:
  name: panorama-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: panorama-api
      network: panorama
  template:
    metadata:
      labels:
        app: panorama-api
        network: panorama
    spec:
      containers:
        - name: panorama-api
          image: docker.io/panorama.api
          imagePullPolicy: Never
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Staging
            - name: ConnectionStrings__Default
              value: Server=mssqlDb;Database=PanoramaDb;User=sa;Password=RcjNvaGQwMQm44eJiaBbDyiMKaT4jndm;TrustServerCertificate=true           
            - name: Kestrel__Endpoints__Http__Url
              value: "http://+:80" # THIS IS EXTREMELY IMPORTANT!!!!!
          ports:
            - name: api
              containerPort: 80 # pod port
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: panorama-api
spec:
  selector:
    app: panorama-api
  ports:
    - name: api
      port: 44312 # exposed service port
      targetPort: 80 # pod port
      protocol: TCP
  # type: LoadBalancer # REMOVE for use in PROD ENV
  type: NodePort # ADD for use in PROD ENV